const wonders = {
    greatWall: {
        name: "Great Wall of China (40.68°N, 117.23°E)",
        description: "The Great Wall of China, built to protect the Chinese states from invasions, stretches over 13,000 miles and is one of the most impressive architectural feats in history.Picture this the rolling hills of northern China stretching across valleys and mountains forming a spine of ancient stones and brick The Great Wall of China a marvel of human determination and engineering Its story begins more than two millennia ago in a land fractured into warring states Each kingdom desperate to protect its borders built its own fortifications But the unification of China under Emperor Qin Shi Huang in 221 BCE marked a turning point The ambitious leader known for his colossal projects envisioned a barrier to ward off invaders from the north The fragmented walls were connected expanded and reinforced a feat achieved through the labor of soldiers peasants and prisoners These early sections made of tamped earth bore witness to the blood and sweat of countless workers As centuries passed successive dynasties left their mark on the Wall The Han Dynasty extended it westward to protect the Silk Road trade routes The Northern Wei Sui and Tang dynasties rebuilt and expanded sections But it was during the Ming Dynasty that the Wall truly became the iconic structure we recognize today Using bricks and stones they crafted a more formidable barrier to defend against the Mongols adding watchtowers and garrisons that dotted the landscape The Great Wall however was never just a military stronghold It also served as a means of communication with signal fires relaying messages across vast distances It shaped economies and cultures standing as a testament to the ingenuity and resilience of the Chinese people Over time as empires rose and fell the Wall faded from its original purpose But its grandeur and significance endured Today it is not just a physical structure but a symbol of unity strength and the spirit of human endeavor Spanning over 13000 miles the Great Wall weaves together stories of triumph and sacrifice a monument to history and a wonder of the world "
    },
    petra: {
        name: "Petra (30.3286°N, 35.4419°E)",
        description: "Petra, located in Jordan, is an archaeological marvel known for its rock-cut architecture and water conduit system. It is a symbol of engineering brilliance and ancient trade.Imagine a city carved entirely into rose-red cliffs hidden in the heart of the desert This is Petra an ancient marvel and a jewel of the Nabataean kingdom Located in modern day Jordan its story begins around the sixth century BCE when the Nabataeans a nomadic Arab people settled in this rugged terrain They transformed the harsh environment into a thriving hub of culture and commerce through ingenious water management systems and strategic trade routes Petra became the center of a vast network connecting Arabia Egypt and the Mediterranean The city flourished between the first century BCE and the first century CE under Nabataean rule They sculpted grand temples tombs and monuments directly into the sandstone cliffs with their most iconic creation being Al Khazneh or the Treasury believed to be a royal tomb or temple Its intricate façade showcases their skill in architecture blending Hellenistic influences with local traditions But Petra's fortunes changed when the Roman Empire annexed the Nabataean kingdom in 106 CE Though still significant its prominence began to fade over time as trade routes shifted and natural disasters struck By the fourth century CE Petra was in decline abandoned and largely forgotten by the wider world Centuries later in 1812 Swiss explorer Johann Ludwig Burckhardt rediscovered Petra introducing its wonders to the world again Today Petra is not only a UNESCO World Heritage Site but also a symbol of the resilience and creativity of its ancient builders Its awe inspiring beauty and rich history continue to captivate visitors from all corners of the globe "
    },
    colosseum: {
        name: "Colosseum (41.8902°N, 12.4922°E)",
        description: "The Colosseum, located in Rome, Italy, is an ancient amphitheater that hosted gladiatorial contests and grand public events in the Roman Empire.Imagine the heart of ancient Rome pulsating with life and grandeur At its core stands the Colosseum a colossal amphitheater that echoes the power and ingenuity of one of historys greatest empires Construction began under Emperor Vespasian of the Flavian dynasty in 72 CE and was completed by his son Titus in 80 CE Built on the site of Emperor Neros Golden House the Colosseum symbolized a new era aimed at returning land to the people The amphitheater could hold up to 50000 spectators who gathered to witness spectacles that ranged from gladiatorial combats to animal hunts and even mock naval battles Elaborately designed it featured tiered seating trapdoors and an underground complex called the hypogeum where animals and gladiators awaited their turn in the arena The Colosseum was more than entertainment it was a tool for political propaganda reinforcing the power and generosity of the emperors Over time as the Roman Empire declined the Colosseum faced natural disasters such as earthquakes and was repurposed for various uses including as a fortress and quarry Despite this it remained an iconic symbol of Rome Rediscovered and preserved in later centuries it stands today as one of the worlds most celebrated architectural marvels and a testament to the enduring legacy of ancient Rome "
    },
    chichenItza: {
        name: "Chichen Itza (20.6831°N, 88.5686°W)",
        description: "Chichen Itza, in Mexico, is an iconic site of the Maya civilization. It features the El Castillo pyramid, a testament to the Mayan understanding of astronomy and architecture.Imagine stepping into the heart of the Yucatan Peninsula where the ancient city of Chichen Itza rises as a testament to the brilliance of the Maya civilization Founded around the sixth century CE Chichen Itza was a vital cultural and economic hub Its strategic location near cenotes or natural sinkholes provided a reliable water source and made it a center for trade and pilgrimage The city thrived during the Terminal Classic and Early Postclassic periods blending Maya traditions with influences from other Mesoamerican cultures such as the Toltecs At its peak the city showcased architectural and astronomical ingenuity with iconic structures like El Castillo or the Temple of Kukulkan This pyramid served as both a temple and a calendar its design reflecting the Maya knowledge of celestial cycles Other marvels include the Great Ball Court the Temple of the Warriors and the Observatory also known as El Caracol which demonstrates their advanced understanding of astronomy Chichen Itza was more than a city it was a ceremonial center where rituals sacrifices and festivals were held But by the late Postclassic period the city declined likely due to political strife and changing trade routes Abandoned but never forgotten Chichen Itza became a symbol of Maya heritage Rediscovered in the modern era it is now a UNESCO World Heritage Site and one of the New Seven Wonders of the World captivating visitors with its history and enduring legacy "
    },
    machuPicchu: {
        name: "Machu Picchu (13.1631°S, 72.5450°W)",
        description: "Nestled high in the Andes Mountains of Peru, Machu Picchu is an Incan citadel known for its sophisticated dry-stone construction and breathtaking views.Nestled high in the Andes Mountains of Peru lies Machu Picchu a breathtaking testament to the ingenuity and vision of the Inca civilization Built in the fifteenth century during the reign of Emperor Pachacuti this citadel served as a royal estate and a ceremonial center Hidden among lush greenery and towering peaks it was an architectural masterpiece blending seamlessly with its natural surroundings The city was constructed using precise stone masonry with temples palaces terraces and aqueducts that showcased the advanced engineering skills of the Incas Key structures like the Temple of the Sun and the Room of the Three Windows reflected their deep connection to astronomy and religion Despite its grandeur Machu Picchu remained largely unknown to the outside world as it was abandoned during the Spanish conquest possibly to protect it from discovery In 1911 American explorer Hiram Bingham brought global attention to the site sparking fascination and awe Today Machu Picchu is a UNESCO World Heritage Site and one of the New Seven Wonders of the World It stands as a symbol of Inca brilliance and resilience drawing millions of visitors each year who marvel at its beauty and legacy "
    },
    tajMahal: {
        name: "Taj Mahal (27.1751°N, 78.0421°E)",
        description: "The Taj Mahal, located in Agra, India, is a white marble mausoleum built by Emperor Shah Jahan in memory of his wife Mumtaz Mahal. It symbolizes eternal love.In the heart of Agra India stands the Taj Mahal a monument of eternal love and unmatched beauty Commissioned in 1632 by the Mughal Emperor Shah Jahan it was built in memory of his beloved wife Mumtaz Mahal who passed away during childbirth This white marble mausoleum is a masterpiece of architecture blending Islamic Persian and Indian styles The construction took over twenty years and involved thousands of artisans and craftsmen Led by architect Ustad Ahmad Lahauri the Taj Mahal features intricate carvings calligraphy and stunning symmetry The central dome rises majestically above the tomb while reflecting pools and lush gardens create a serene setting The Taj Mahal is more than just a tomb it is a symbol of devotion and artistic excellence Over the centuries it has weathered time and political changes standing resilient as a UNESCO World Heritage Site and one of the New Seven Wonders of the World Today the Taj Mahal continues to inspire millions of visitors with its timeless beauty and the profound love story it represents "
    },
    christRedeemer: {
        name: "Christ the Redeemer (22.9519°S, 43.2105°W)",
        description: "Christ the Redeemer, in Rio de Janeiro, Brazil, is an iconic statue symbolizing peace and Christianity. It stands tall as a beacon of hope and unity.High above the vibrant city of Rio de Janeiro Brazil stands Christ the Redeemer a monumental statue that has become a symbol of faith and unity The story of this iconic landmark begins in the mid nineteenth century when the idea of a Christian monument on Mount Corcovado was first proposed However it was not until the early twentieth century that the vision took shape In 1921 the Roman Catholic Archdiocese of Rio de Janeiro launched a campaign to build a statue of Christ to commemorate the centenary of Brazil's independence from Portugal Designed by Brazilian engineer Heitor da Silva Costa and sculpted by French artist Paul Landowski the statue was constructed between 1922 and 1931 Made of reinforced concrete and clad in soapstone it stands 30 meters tall with arms outstretched spanning 28 meters The statue was inaugurated on October 12 1931 and quickly became a cultural and spiritual icon Over the years Christ the Redeemer has withstood the test of time enduring natural elements and even lightning strikes Today it is not only a UNESCO World Heritage Site but also one of the New Seven Wonders of the World attracting millions of visitors who marvel at its grandeur and the breathtaking views of Rio de Janeiro "
    }
};

function showDetails(wonderKey) {
    const wonders = wonders[wonderKey]; 
    if (wonder) {
        document.getElementById("wonderName").innerText = wonder.name;
        document.getElementById("wonderDescription").innerText = wonder.description;
        
        document.querySelector("main").style.display = "none";
        document.getElementById("details").style.display = "block";
    } else {
        alert("Details for this wonder are not available."); 
    }
}

function hideDetails() {
    
    document.querySelector("main").style.display = "block";
    document.getElementById("details").style.display = "none";
}const wonder = {
    greatWall: {
        name: "Great Wall of China (40.68°N, 117.23°E)",
        description: "The Great Wall of China, built to protect the Chinese states from invasions, stretches over 13,000 miles and is one of the most impressive architectural feats in history.Picture this the rolling hills of northern China stretching across valleys and mountains forming a spine of ancient stones and brick The Great Wall of China a marvel of human determination and engineering Its story begins more than two millennia ago in a land fractured into warring states Each kingdom desperate to protect its borders built its own fortifications But the unification of China under Emperor Qin Shi Huang in 221 BCE marked a turning point The ambitious leader known for his colossal projects envisioned a barrier to ward off invaders from the north The fragmented walls were connected expanded and reinforced a feat achieved through the labor of soldiers peasants and prisoners These early sections made of tamped earth bore witness to the blood and sweat of countless workers As centuries passed successive dynasties left their mark on the Wall The Han Dynasty extended it westward to protect the Silk Road trade routes The Northern Wei Sui and Tang dynasties rebuilt and expanded sections But it was during the Ming Dynasty that the Wall truly became the iconic structure we recognize today Using bricks and stones they crafted a more formidable barrier to defend against the Mongols adding watchtowers and garrisons that dotted the landscape The Great Wall however was never just a military stronghold It also served as a means of communication with signal fires relaying messages across vast distances It shaped economies and cultures standing as a testament to the ingenuity and resilience of the Chinese people Over time as empires rose and fell the Wall faded from its original purpose But its grandeur and significance endured Today it is not just a physical structure but a symbol of unity strength and the spirit of human endeavor Spanning over 13000 miles the Great Wall weaves together stories of triumph and sacrifice a monument to history and a wonder of the world "
    },
    petra: {
        name: "Petra (30.3286°N, 35.4419°E)",
        description: "Petra, located in Jordan, is an archaeological marvel known for its rock-cut architecture and water conduit system. It is a symbol of engineering brilliance and ancient trade.Imagine a city carved entirely into rose-red cliffs hidden in the heart of the desert This is Petra an ancient marvel and a jewel of the Nabataean kingdom Located in modern day Jordan its story begins around the sixth century BCE when the Nabataeans a nomadic Arab people settled in this rugged terrain They transformed the harsh environment into a thriving hub of culture and commerce through ingenious water management systems and strategic trade routes Petra became the center of a vast network connecting Arabia Egypt and the Mediterranean The city flourished between the first century BCE and the first century CE under Nabataean rule They sculpted grand temples tombs and monuments directly into the sandstone cliffs with their most iconic creation being Al Khazneh or the Treasury believed to be a royal tomb or temple Its intricate façade showcases their skill in architecture blending Hellenistic influences with local traditions But Petra's fortunes changed when the Roman Empire annexed the Nabataean kingdom in 106 CE Though still significant its prominence began to fade over time as trade routes shifted and natural disasters struck By the fourth century CE Petra was in decline abandoned and largely forgotten by the wider world Centuries later in 1812 Swiss explorer Johann Ludwig Burckhardt rediscovered Petra introducing its wonders to the world again Today Petra is not only a UNESCO World Heritage Site but also a symbol of the resilience and creativity of its ancient builders Its awe inspiring beauty and rich history continue to captivate visitors from all corners of the globe "
    },
    colosseum: {
        name: "Colosseum (41.8902°N, 12.4922°E)",
        description: "The Colosseum, located in Rome, Italy, is an ancient amphitheater that hosted gladiatorial contests and grand public events in the Roman Empire.Imagine the heart of ancient Rome pulsating with life and grandeur At its core stands the Colosseum a colossal amphitheater that echoes the power and ingenuity of one of historys greatest empires Construction began under Emperor Vespasian of the Flavian dynasty in 72 CE and was completed by his son Titus in 80 CE Built on the site of Emperor Neros Golden House the Colosseum symbolized a new era aimed at returning land to the people The amphitheater could hold up to 50000 spectators who gathered to witness spectacles that ranged from gladiatorial combats to animal hunts and even mock naval battles Elaborately designed it featured tiered seating trapdoors and an underground complex called the hypogeum where animals and gladiators awaited their turn in the arena The Colosseum was more than entertainment it was a tool for political propaganda reinforcing the power and generosity of the emperors Over time as the Roman Empire declined the Colosseum faced natural disasters such as earthquakes and was repurposed for various uses including as a fortress and quarry Despite this it remained an iconic symbol of Rome Rediscovered and preserved in later centuries it stands today as one of the worlds most celebrated architectural marvels and a testament to the enduring legacy of ancient Rome "
    },
    chichenItza: {
        name: "Chichen Itza (20.6831°N, 88.5686°W)",
        description: "Chichen Itza, in Mexico, is an iconic site of the Maya civilization. It features the El Castillo pyramid, a testament to the Mayan understanding of astronomy and architecture.Imagine stepping into the heart of the Yucatan Peninsula where the ancient city of Chichen Itza rises as a testament to the brilliance of the Maya civilization Founded around the sixth century CE Chichen Itza was a vital cultural and economic hub Its strategic location near cenotes or natural sinkholes provided a reliable water source and made it a center for trade and pilgrimage The city thrived during the Terminal Classic and Early Postclassic periods blending Maya traditions with influences from other Mesoamerican cultures such as the Toltecs At its peak the city showcased architectural and astronomical ingenuity with iconic structures like El Castillo or the Temple of Kukulkan This pyramid served as both a temple and a calendar its design reflecting the Maya knowledge of celestial cycles Other marvels include the Great Ball Court the Temple of the Warriors and the Observatory also known as El Caracol which demonstrates their advanced understanding of astronomy Chichen Itza was more than a city it was a ceremonial center where rituals sacrifices and festivals were held But by the late Postclassic period the city declined likely due to political strife and changing trade routes Abandoned but never forgotten Chichen Itza became a symbol of Maya heritage Rediscovered in the modern era it is now a UNESCO World Heritage Site and one of the New Seven Wonders of the World captivating visitors with its history and enduring legacy "
    },
    machuPicchu: {
        name: "Machu Picchu (13.1631°S, 72.5450°W)",
        description: "Nestled high in the Andes Mountains of Peru, Machu Picchu is an Incan citadel known for its sophisticated dry-stone construction and breathtaking views.Nestled high in the Andes Mountains of Peru lies Machu Picchu a breathtaking testament to the ingenuity and vision of the Inca civilization Built in the fifteenth century during the reign of Emperor Pachacuti this citadel served as a royal estate and a ceremonial center Hidden among lush greenery and towering peaks it was an architectural masterpiece blending seamlessly with its natural surroundings The city was constructed using precise stone masonry with temples palaces terraces and aqueducts that showcased the advanced engineering skills of the Incas Key structures like the Temple of the Sun and the Room of the Three Windows reflected their deep connection to astronomy and religion Despite its grandeur Machu Picchu remained largely unknown to the outside world as it was abandoned during the Spanish conquest possibly to protect it from discovery In 1911 American explorer Hiram Bingham brought global attention to the site sparking fascination and awe Today Machu Picchu is a UNESCO World Heritage Site and one of the New Seven Wonders of the World It stands as a symbol of Inca brilliance and resilience drawing millions of visitors each year who marvel at its beauty and legacy "
    },
    tajMahal: {
        name: "Taj Mahal (27.1751°N, 78.0421°E)",
        description: "The Taj Mahal, located in Agra, India, is a white marble mausoleum built by Emperor Shah Jahan in memory of his wife Mumtaz Mahal. It symbolizes eternal love.In the heart of Agra India stands the Taj Mahal a monument of eternal love and unmatched beauty Commissioned in 1632 by the Mughal Emperor Shah Jahan it was built in memory of his beloved wife Mumtaz Mahal who passed away during childbirth This white marble mausoleum is a masterpiece of architecture blending Islamic Persian and Indian styles The construction took over twenty years and involved thousands of artisans and craftsmen Led by architect Ustad Ahmad Lahauri the Taj Mahal features intricate carvings calligraphy and stunning symmetry The central dome rises majestically above the tomb while reflecting pools and lush gardens create a serene setting The Taj Mahal is more than just a tomb it is a symbol of devotion and artistic excellence Over the centuries it has weathered time and political changes standing resilient as a UNESCO World Heritage Site and one of the New Seven Wonders of the World Today the Taj Mahal continues to inspire millions of visitors with its timeless beauty and the profound love story it represents "
    },
    christRedeemer: {
        name: "Christ the Redeemer (22.9519°S, 43.2105°W)",
        description: "Christ the Redeemer, in Rio de Janeiro, Brazil, is an iconic statue symbolizing peace and Christianity. It stands tall as a beacon of hope and unity.High above the vibrant city of Rio de Janeiro Brazil stands Christ the Redeemer a monumental statue that has become a symbol of faith and unity The story of this iconic landmark begins in the mid nineteenth century when the idea of a Christian monument on Mount Corcovado was first proposed However it was not until the early twentieth century that the vision took shape In 1921 the Roman Catholic Archdiocese of Rio de Janeiro launched a campaign to build a statue of Christ to commemorate the centenary of Brazil's independence from Portugal Designed by Brazilian engineer Heitor da Silva Costa and sculpted by French artist Paul Landowski the statue was constructed between 1922 and 1931 Made of reinforced concrete and clad in soapstone it stands 30 meters tall with arms outstretched spanning 28 meters The statue was inaugurated on October 12 1931 and quickly became a cultural and spiritual icon Over the years Christ the Redeemer has withstood the test of time enduring natural elements and even lightning strikes Today it is not only a UNESCO World Heritage Site but also one of the New Seven Wonders of the World attracting millions of visitors who marvel at its grandeur and the breathtaking views of Rio de Janeiro "
    }
};

function showDetails(wonderKey) {
    const wonder = wonders[wonderKey]; 
    if (wonder) {
        document.getElementById("wonderName").innerText = wonder.name;
        document.getElementById("wonderDescription").innerText = wonder.description;
        
        document.querySelector("main").style.display = "none";
        document.getElementById("details").style.display = "block";
    } else {
        alert("Details for this wonder are not available."); 
    }
}

function hideDetails() {
    
    document.querySelector("main").style.display = "block";
    document.getElementById("details").style.display = "none";
}